// src/lib/components/common/ColorInput.tsx
import { useMemo } from 'react';
import paper, { Color } from 'paper';
import Input from './Input';

interface ColorInputProps {
	color: Array<paper.Color | null>;
	setColor: (color: paper.Color) => void;
}

const getColorString = (color: Array<paper.Color | null>) => {
	const colors = color.filter(Boolean) as paper.Color[];
	if (colors.length === 0) return undefined;

	const [firstColor] = colors;
	if (colors.length === color.length && colors.every((itemColor) => itemColor.equals(firstColor))) {
		return firstColor.toCSS(true);
	}

	return 'Mixed';
};

const normalizeHex = (value: string) => {
	let inputColor = value.trim();
	if (inputColor.startsWith('#')) {
		inputColor = inputColor.slice(1);
	}

	if (!/^[0-9a-fA-F]+$/.test(inputColor)) {
		return null;
	}

	while (inputColor.length < 6) {
		inputColor += inputColor;
	}

	return `#${inputColor.slice(0, 6)}`;
};

const ColorInput = ({ color, setColor }: ColorInputProps) => {
	const colorString = useMemo(() => getColorString(color), [color]);
	const displayColor = colorString === undefined ? 'None' : colorString;
	const colorInputValue = colorString?.startsWith('#') ? colorString : '#000000';

	const checkAndSetColor = (event: React.ChangeEvent<HTMLInputElement>) => {
		const normalized = normalizeHex(event.currentTarget.value);
		if (!normalized) return;

		setColor(new Color(normalized));
	};

	return (
		<div className="color-input-wrapper">
			<input
				type="color"
				value={colorInputValue}
				onInput={(event) => setColor(new Color(event.currentTarget.value))}
				aria-label="Color picker"
			/>
			<Input
				type="text"
				value={displayColor}
				onFocus={(event) => event.currentTarget.select()}
				onChange={checkAndSetColor}
			/>
		</div>
	);
};

export default ColorInput;

// src/lib/components/common/ColorInput.svelte
<script lang="ts">
	import paper, { Color } from 'paper';
	import Input from './Input.svelte';

	export let color: paper.Color[];
	export let setColor: (arg0: paper.Color) => void;

	// if all colors are the same, return that color
	// otherwise, return "Mixed"
	$: getColorString = () => {
		if (color.length === 0) return undefined;

		const firstColor = color[0];
		if (color.every((c) => c.equals(firstColor))) {
			return firstColor.toCSS(true);
		}

		return 'Mixed';
	};

	$: colorString = getColorString();
	$: displayColor = colorString === undefined ? 'None' : colorString;

    function checkAndSetColor(e: Event) {
        const target = e.target as HTMLInputElement;
        let inputColor = target.value;

        // if starts with #, remove it
        if (inputColor.startsWith('#')) {
            inputColor = inputColor.slice(1);
        }

        // if inputColor is not 6 digits, repeat until it is
        if (inputColor.length !== 6) {
            while (inputColor.length < 6) {
                inputColor += inputColor;
            }
            inputColor = inputColor.slice(0, 6);
        }

        const newColor = new Color(`#${inputColor}`);
        setColor(newColor);
    }
</script>

<div class="wrapper">
	<input
		type="color"
		bind:value={colorString}
		on:input={(e) => setColor(new Color(e.target?.value))}
	/>
	<Input
		type="text"
		bind:value={displayColor}
		onFocus={(e) => e.target.select()}
        onChange={checkAndSetColor}
	/>
</div>

<style>
	.wrapper {
		flex-grow: 1;
		min-width: 0;
		position: relative;
	}
	input[type='color'] {
		position: absolute;
		left: 0;
		background: none;
		border-radius: 2px;
		border-width: 0;
		width: 34px;
		padding: 6px;
		height: 100%;
	}

	input[type='color']::-webkit-color-swatch-wrapper {
		padding: 0;
	}

	input[type='color']::-webkit-color-swatch {
		border-radius: 4px;
		border-width: 0;
	}

	.wrapper :global(input[type='text']) {
		padding: 8px 8px;
		padding-left: 35px;
		border-top-right-radius: 0 !important;
		border-bottom-right-radius: 0 !important;
	}
</style>
