// src/lib/components/common/OpacityInput.tsx
import Input from './Input';

interface OpacityInputProps {
	opacity: number;
	setOpacity: (opacity: number) => void;
}

const OpacityInput = ({ opacity, setOpacity }: OpacityInputProps) => {
	const displayOpacity = `${Math.round(opacity * 100)}%`;

	const updateOpacity = (event: React.ChangeEvent<HTMLInputElement>) => {
		const nextOpacity = parseFloat(event.currentTarget.value) / 100;
		if (Number.isNaN(nextOpacity)) return;
		setOpacity(nextOpacity);
	};

	return (
		<div className="opacity-input-wrapper">
			<Input
				type="text"
				value={displayOpacity}
				onChange={updateOpacity}
				onFocus={(event) => event.currentTarget.select()}
			/>
		</div>
	);
};

export default OpacityInput;

// src/lib/components/common/OpacityInput.svelte
<script lang="ts">
	import Input from './Input.svelte';

	$: ({ opacity, setOpacity, ...inputProps } = $$props);

	$: displayOpacity = `${Math.round(opacity * 100)}%`;

	const updateOpacity = (e: Event) => {
		const target = e.target as HTMLInputElement;
		const opacity = parseFloat(target.value) / 100;
		if (isNaN(opacity)) return;
		setOpacity(opacity);
	};
</script>

<div id="wrapper" class="min-w-0" style="flex-basis: 100px;">
	<Input
		type="text"
		value={displayOpacity}
		onChange={updateOpacity}
		onFocus={(e) => {
			e.target.select();
		}}
		{...inputProps}
	/>
</div>

<style>
	#wrapper :global(input) {
		border-top-left-radius: 0 !important;
		border-bottom-left-radius: 0 !important;
	}
</style>
