// src/lib/components/common/VisibilityToggle.svelte
<script>
	import Icon from "$lib/components/Icon.svelte";


    /**
	 * @type {boolean}
	 */
     export let visible;
     $: name = visible ? "eye-open" : "eye-closed";

     /**
	 * @type {(arg0: boolean) => any}
	 */
      export let setVisible;
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div class="wrapper" on:click={() => setVisible(!visible)}>
    <Icon {name} />
</div>

<style lang="scss">
    .wrapper {
        padding: 8px;
        border-radius: 8px;

        &:hover {
            background-color: #303437;
        }
    }
</style>

// src/lib/components/common/VisibilityToggle.tsx
import Icon from '$lib/components/Icon';

interface VisibilityToggleProps {
	visible: boolean;
	setVisible: (visible: boolean) => void;
}

const VisibilityToggle = ({ visible, setVisible }: VisibilityToggleProps) => {
	return (
		<button
			type="button"
			className="visibility-toggle"
			aria-label={visible ? 'Hide' : 'Show'}
			title={visible ? 'Hide' : 'Show'}
			onClick={() => setVisible(!visible)}
		>
			<Icon name={visible ? 'eye-open' : 'eye-closed'} />
		</button>
	);
};

export default VisibilityToggle;
